<header>
  <nav class="navbar navbar-default" role="navigation">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="<?php echo $this->url('home'); ?>"><i class="fa fa-stack-overflow"></i> Photostack</a>
      </div>
      <div class="navbar-collapse collapse" id="loginForm">
        <ul class="nav navbar-nav">
          <li><a href="<?php echo $this->url('home'); ?>">Home</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galleries <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php foreach ($this->usersList as $user)
              {
              ?>
              <li>
                 <a href="<?php echo $this->url('gallery', array('user' => $user['username'])); ?>" title="<?php echo $user['username']; ?>">
                    <i class='fa fa-folder-open'></i> <?php echo $user['username']; ?>
                  </a>
              </li>
              <?php
              }
               ?>
            </ul>
          </li>
        </ul>
        <div class="navbar-form navbar-right">
          <a class="btn btn-success btn-sm" href="<?php echo $this->url('signin'); ?>"> Sign In</a>
        </div>
      </div>
    </div><!--/.navbar-collapse -->
  </nav>
</header><!-- /header -->
<section class="container">
  <div id="form" class="form-signin">
    <?php
    $form->setAttribute('action', $this->url('signup'))
    ->prepare();
    echo $this->form()->openTag($form);
    $users = $form->get('users');
    ?>
    <h2 class="form-signin-heading">Want to sign up ?</h2>
    <hr>
    <div class='form-group'>
        <?php echo $this->formRow($users->get('mail')); ?>
    </div>
    <div class='form-group'>
        <?php echo $this->formRow($users->get('username')); ?>
    </div>
    <div class='form-group'>
        <?php echo $this->formRow($users->get('age')); ?>
    </div>
    <div class='form-group' id='captcha'>
        <?php echo $this->formRow($users->get('captcha')); ?>
    </div>
    <?php  if (isset($this->message)) { ?>
      <div class='alert alert-warning alert-dismissable'>
          <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
          <?php echo $this->message ?>
      </div>
      <?php } ?>
    <div class='form-group'>
        <?php echo $this->formElement($form->get('submit')); ?>
    </div>
    <div class='form-group'>
        <?php echo $this->formHidden($form->get('csrf'));
              echo $this->form()->closeTag(); ?>
    <a class="btn btn-link btn-sm" id="btn-return" href="<?php echo $this->url('home'); ?>"><i class="fa fa-angle-double-right"></i> back to home</a>
  </div>
</section>
