<header>
  <nav class="navbar navbar-default" role="navigation">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">Photostack</a>
      </div>
      <div class="navbar-collapse collapse">
        <div class="navbar-form navbar-right">
          <a class="btn btn-success btn-sm" href="<?php echo $this->url('signin'); ?>"> Sign In</a>
          <a class="btn btn-info btn-sm" href="<?php echo $this->url('signup'); ?>"> Register</a>
        </div>
      </div>
    </div><!--/.navbar-collapse -->
  </nav>
</header><!-- /header -->
<section class="container">
  <div id="form" class="form-signin">
    <?php
    $form->setAttribute('action', $this->url('signin'))
    ->prepare();
    echo $this->form()->openTag($form);
    $users = $form->get('users');
    ?>
    <h2 class="form-signin-heading">Please sign in</h2>
    <hr>
    <?
    echo "<div class='form-group'>";
    echo $this->formRow($users->get('mail'));
    echo "</div>";
    echo "<div class='form-group'>";
    echo $this->formRow($users->get('password'));
    echo "</div>";
    echo "<div class='form-group'>";
    echo $this->formElement($form->get('submit'));
    echo "<div class='form-group'>";
    echo $this->formHidden($form->get('csrf'));
    echo $this->form()->closeTag(); ?>
    <a class="btn btn-link btn-sm" id="btn-return" href="<?php echo $this->url('home'); ?>"><i class="fa fa-angle-double-right"></i> return to home</a>
  </div>
</section>