<header>
    <nav class="navbar navbar-default" role="navigation">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home'); ?>"><i class="fa fa-stack-overflow"></i> Photostack</a>
            </div>
            <div class="navbar-collapse collapse" id="loginForm">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->url('home'); ?>">Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galleries <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <?php foreach ($this->usersList as $user)
                            {
                                ?>
                                <li>
                                    <a href="<?php echo $this->url('gallery', array('user' => $user['username'])); ?>" title="<?php echo $user['username']; ?>">
                                        <i class='fa fa-folder-open'></i> <?php echo $user['username']; ?>
                                    </a>
                                </li>
                            <?php
                            }
                            ?>
                        </ul>
                    </li>
                </ul>
                <div class='navbar-form navbar-right'>
                    <a href='<?php echo $this->url('logout') ?>'><button class='btn btn-danger btn-sm' type='submit'><i class="fa fa-arrow-circle-right"></i>&nbsp;&nbsp;Log out</button></a>
                </div>
            </div>
        </div><!--/.navbar-collapse -->
    </nav>
</header><!-- /header -->
<section class="container">
        <div class="page-header">
            <h1>Users list</h1>
        </div>
        <table class="table table-bordered table-hover table-responsive">
            <thead>
            <tr>
                <th>Username</th>
                <th>State</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->userAuthList as $user) { ?>
            <tr>
                <td><?php echo $user['username'] ?></td>
                <td><?php
                    if($user['isBlocked'] === null || $user['isBlocked'] == 0) {

                        echo "<span class='label label-success'>active</span>";

                    } else if($user['isBlocked'] == 1) {

                        echo "<span class='label label-warning'>blocked</span>";
                    }
             ?></td>
                <td>
                    <a href="<?php echo $this->url('unlock', array('user' => $user['username'])); ?>" class="btn btn-default btn-xs"><i class="fa fa-unlock"></i> Unlock</a>
                    &nbsp;
                    <a href="<?php echo $this->url('delete', array('user' => $user['username'])); ?>" class="btn btn-danger btn-xs"><i class="fa fa-times"></i> Delete</a>
                </td>
            </tr>
            <?php } ?>
            </tbody>
        </table>
        </div>
</section>