<header>
    <nav class="navbar navbar-default" role="navigation">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home'); ?>"><i class="fa fa-stack-overflow"></i> Photostack</a>
            </div>
            <div class="navbar-collapse collapse" id="loginForm">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->url('home'); ?>">Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galleries <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <?php foreach ($this->usersList as $user)
                            {
                                ?>
                                <li>
                                    <a href="<?php echo $this->url('gallery', array('user' => $user['username'])); ?>" title="<?php echo $user['username']; ?>">
                                        <i class='fa fa-folder-open'></i> <?php echo $user['username']; ?>
                                    </a>
                                </li>
                            <?php
                            }
                            ?>
                        </ul>
                    </li>
                </ul>
                <div class='navbar-form navbar-right'>
                    <a href='<?php echo $this->url('logout') ?>'><button class='btn btn-danger btn-sm' type='submit'><i class="fa fa-arrow-circle-right"></i>&nbsp;&nbsp;Log out</button></a>
                </div>
            </div>
        </div><!--/.navbar-collapse -->
    </nav>
</header><!-- /header -->
<section class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="row clearfix">
                <section class="col-md-12 column" id="gallery">
                    <div class="page-header">
                        <h1>Vos images</h1>
                        <button type="button" class="upload btn btn-info btn-md" data-toggle="modal" data-target="#upload"><i class="fa fa-picture-o"></i> Upload photo</button>
                    </div>
                    <div class="row">
                        <?php foreach ($this->images as $image) { ?>
                        <figure class="col-xs-6 col-md-3 col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="<?php echo $image['url'] ?>" alt="<?php echo ($image['id']."_".str_replace(' ', '_', $image['name'])); ?>">
                            </a>
                            <figcaption>
                                <p><?php echo str_replace('-', '/', $image['uploaded']).", ".$image['weight']."mo" ?></p>
                                <hr>
                                <ul>
                                    <li><h4><span class="label label-primary"><?php echo "#".$image['publishId'] ?></span></h4></li>
                                    <li>
                                        <a href="<?php echo $this->url('remove', array('id' => $image['id'])); ?>"
                                           class="btn btn-delete btn-danger btn-xs"><i class="fa fa-times"></i> Delete</a>
                                    </li>
                                </ul>
                            </figcaption>
                        </figure>
                        <?php } ?>
                    </div>
                </section>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel2">Delete this image ?</h4>
            </div>
            <div class="modal-body">
                <div class="center-block">
                    <button type="button" class="btn btn-default" id="cancel">No</button>
                    &nbsp;
                    <button type="button" class="btn btn-primary" id="confirm">Yes</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="upload" tabindex="-1" role="dialog" aria-labelledby="modal-upload" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Adding a photo</h4>
            </div>
            <div class="modal-body">
                <?php $form->prepare(); ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class='form-group'>
                    <?php $fileElement = $form->get('image-file');
                    echo $this->formFile($fileElement);
                    echo $this->formElementErrors($fileElement); ?>
                <button type="button" class="upload-btn btn btn-primary">Upload</button>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<?php $this->inlineScript()->appendFile('/js/upload.js'); ?>