<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('PhotoStack &middot; '. $this->translate('Web gallery'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/uikit.gradient.min.css') 
    ->prependStylesheet($this->basePath() . '/css/main.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/uikit.min.js')
    ->prependFile($this->basePath() . '/js/html5shiv.js')
    ->prependFile($this->basePath() . '/js/modernizr.js')
    ->prependFile($this->basePath() . '/js/jquery.js')
    ; ?>

</head>
<body>
    <div id="wrapper">
            <?php echo $this->content; ?>
    </div>
        <?php echo $this->inlineScript() ?>   
</body>
    </html>
