<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('PhotoStack &middot; '. $this->translate('Web gallery'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css') 
    ->prependStylesheet($this->basePath() . '/Font-Awesome/css/font-awesome.min.css')
    ->prependStylesheet($this->basePath() . '/fancybox/source/jquery.fancybox.css?v=2.1.5')
    ->prependStylesheet($this->basePath() . '/css/style.css'); ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/fancybox.js')
    ->prependFile($this->basePath() . '/fancybox/source/jquery.fancybox.js?v=2.1.5')    
    ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/html5shiv.js')
    ->prependFile($this->basePath() . '/js/modernizr.js')
    ->prependFile($this->basePath() . 'http://codeorigin.jquery.com/jquery-1.10.2.min.js') ?>

</head>
<body>
    <div id="wrapper">
            <?php echo $this->content; ?>
    </div>
        <?php echo $this->inlineScript() ?>
</body>
    </html>
