<header>
            <nav class="uk-navbar">
                <a href="#" class="uk-navbar-brand">PhotoStack</a>

                <div class="uk-navbar-content uk-navbar-flip  uk-hidden-small">
                    <a class="uk-button uk-button-success" href="<?php $this->url('auth', array('action' => 'login')); ?>"><i class="uk-icon-lock"></i> Login</a>
                    <a class="uk-button uk-button-primary" href="<?php $this->url('auth', array('action' => 'sign')); ?>"><i class="uk-icon-signin"></i> Sign Up</a>
                </div>
            </nav>
        </header><!-- /header -->
        <section class="container">
        </section>
        <aside class="gallery-list">
    <nav>
        <div class="uk-button-dropdown" data-uk-dropdown>
            <button class="uk-button" type="submit"><i class="uk-icon-picture"></i>  Galleries</button>
            <div class="uk-dropdown uk-dropdown-small">
                <ul class="uk-nav uk-nav-dropdown">
                    <?php foreach ($this->users as $user)
                    {
                      echo ("<li>
                        <a href='#".$user['username']."' title='".$user['username']."'>
                        <i class='uk-icon-folder-close'></i> ".$user['username']."
                        </a>
                        </li>");
                    } ?>
                </ul>
            </div>
        </div>
    </nav>
</aside>
<?php echo ("<h2 class='uk-text-large gallery-title'>".$this->user."'s gallery</h2>"); ?>
<section class="photo-panel">
    <ul>
        <?php
        foreach ($this->images as $image)
        {
            echo ("<li>
                <figure class='uk-thumbnail uk-overlay-toggle'>
                <div class='uk-overlay'>
                <img src='".$image['url']."' alt='".$image['id']."_".str_replace(' ', '_', $image['name'])."'>
                <div class='uk-overlay-area'></div>
                </div>
                <figcaption class='uk-thumbnail-caption'><small>Un chat</small></figcaption>
                </figure>
                </li>");
            } ?>
        </ul>
    </section>
    <div id="signup" class="uk-modal">
        <div id="signup-modal" class="uk-modal-dialog uk-modal-dialog-slide">
            <a class="uk-modal-close uk-close"></a>
            <?php
            $loginForm->setAttribute('action', $this->url('home'))
            ->prepare();

            echo $this->form()->openTag($signupForm);
            $users = $signupForm->get('users');
            ?>
            <h3><i class="uk-icon-bookmark"></i> SIGN UP</h3>
            <hr>
            <?

            echo "<div class='uk-form-row'>";
            echo $this->formRow($users->get('mail'));
            echo "</div>";
            echo "<div class='uk-form-row'>";
             echo $this->formRow($users->get('username'));
            echo "</div>";
            echo "<div class='uk-form-row'>";
             echo $this->formRow($users->get('age'));
            echo "</div>";
            echo "<div class='uk-form-row'>";
            echo $this->formElement($signupForm->get('submit'));
            echo "</div>";
            echo $this->formHidden($signupForm->get('csrf'));
            echo $this->form()->closeTag(); ?>
        </div>
    </div>
