<header>
  <nav class="navbar navbar-default" role="navigation">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">Photostack</a>
      </div>
      <div class="navbar-collapse collapse" id="loginForm">
        <ul class="nav navbar-nav">
          <li class="active"><a href="<?php echo $this->url('home'); ?>">Home</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galleries <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php foreach ($this->usersList as $user)
              {
              ?>
              <li>
                 <a href="<?php echo $this->url('gallery', array('user' => $user['username'])); ?>" title="<?php echo $user['username']; ?>">
                    <i class='fa fa-folder-open'></i> <?php echo $user['username']; ?>
                  </a>
              </li>
              <?php
              }
               ?>
            </ul>
          </li>
        </ul>
        <div class='navbar-form navbar-right'>
          <a href='<?php echo $this->url('account') ?>'><button class='btn btn-success btn-sm' type='submit'><i class="fa fa-user"></i>&nbsp;&nbsp;My account</button></a>
          <a href='<?php echo $this->url('logout') ?>'><button class='btn btn-danger btn-sm' type='submit'><i class="fa fa-arrow-circle-right"></i>&nbsp;&nbsp;Log out</button></a>
        </div>
      </div>
    </div><!--/.navbar-collapse -->
  </nav>
</header><!-- /header -->
<section class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="row clearfix">
                <section class="col-md-12 column" id="gallery">
                    <div class="page-header">
                      <?php echo ("<h2>".$this->user."'s<small> gallery</small></h2>"); ?>
                    </div>
                    <div class="row">
                      <?php
                      foreach ($this->images as $image)
                      {
                        echo ("<figure class='col-xs-10 col-sm-6 col-md-3 col-lg-2'>
                          <a href='".$image['url']."' class='thumbnail fancybox'>
                            <img src='".$image['url']."' alt='".$image['id']."_".str_replace(' ', '_', $image['name'])."'>
                          </a>
                        </figure>");
                      } ?>
                </section>
            </div>
        </div>
    </div>
</section>