<header>
  <nav class="navbar navbar-default" role="navigation">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">Photostack</a>
      </div>
      <div class="navbar-collapse collapse" id="loginForm">
        <div class='navbar-form navbar-right'>
          <a href='<?php echo $this->url('home') ?>'><button class='btn btn-success btn-sm' type='submit'><i class="fa fa-user"></i>&nbsp;&nbsp;My account</button></a>
          <a href='<?php echo $this->url('logout') ?>'><button class='btn btn-danger btn-sm' type='submit'><i class="fa fa-arrow-circle-right"></i>&nbsp;&nbsp;Log out</button></a>
        </div>
      </div>
    </div><!--/.navbar-collapse -->
  </nav>
</header><!-- /header -->
<section class="container">
</section>
<aside class="col-xs-3 .col-md-5">
  <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      <i class="fa fa-camera"></i> Galleries
    </button>
    <ul class="dropdown-menu">
      <?php foreach ($this->usersList as $user)
      {
        echo ("<li>
          <a href='#".$user['username']."' title='".$user['username']."'>
          <i class='fa fa-folder-open'></i> ".$user['username']."
          </a>
          </li>");
        } ?>
      </ul>
    </div>
  </aside>

  <section class="col-xs-12 col-sm-6 col-md-8" id="gallery">
    <div class="page-header">
      <?php echo ("<h2>".$this->user."'s<small> gallery</small></h2>"); ?>
    </div>
    <div class="row">
      <?php
      foreach ($this->images as $image)
      {
        echo ("<figure class='col-xs-10 col-sm-6 col-md-3 col-lg-2'>
          <a href='".$image['url']."' class='thumbnail'>
          <img src='".$image['url']."' alt='".$image['id']."_".str_replace(' ', '_', $image['name'])."'>
          </a>
          </figure>");
        } ?>
      </div>
    </section>